#默认使用配置
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://47.92.224.127:3306/aaaccount
    username: root
    password: 1111
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: true
    #hibernate ddl auto(validate,create,update,create-drop)
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect