package com.dawson.aaaccount.entity;

public class DaybookPicture {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daybook_picture.id
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daybook_picture.daybook
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    private String daybook;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daybook_picture.picture
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    private String picture;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daybook_picture.id
     *
     * @return the value of daybook_picture.id
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daybook_picture.id
     *
     * @param id the value for daybook_picture.id
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daybook_picture.daybook
     *
     * @return the value of daybook_picture.daybook
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    public String getDaybook() {
        return daybook;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daybook_picture.daybook
     *
     * @param daybook the value for daybook_picture.daybook
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    public void setDaybook(String daybook) {
        this.daybook = daybook == null ? null : daybook.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daybook_picture.picture
     *
     * @return the value of daybook_picture.picture
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    public String getPicture() {
        return picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daybook_picture.picture
     *
     * @param picture the value for daybook_picture.picture
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    public void setPicture(String picture) {
        this.picture = picture == null ? null : picture.trim();
    }
}