package com.dawson.aaaccount.entity;

import java.math.BigDecimal;
import java.util.Date;

public class DayBook {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daybook.id
     *
     * @mbg.generated Fri Jul 27 22:56:47 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daybook.money
     *
     * @mbg.generated Fri Jul 27 22:56:47 CST 2018
     */
    private BigDecimal money;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daybook.recorder
     *
     * @mbg.generated Fri Jul 27 22:56:47 CST 2018
     */
    private String recorder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daybook.des
     *
     * @mbg.generated Fri Jul 27 22:56:47 CST 2018
     */
    private String des;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daybook.date
     *
     * @mbg.generated Fri Jul 27 22:56:47 CST 2018
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daybook.family
     *
     * @mbg.generated Fri Jul 27 22:56:47 CST 2018
     */
    private String family;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daybook.payer
     *
     * @mbg.generated Fri Jul 27 22:56:47 CST 2018
     */
    private String payer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daybook.category
     *
     * @mbg.generated Fri Jul 27 22:56:47 CST 2018
     */
    private String category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daybook.settle
     *
     * @mbg.generated Fri Jul 27 22:56:47 CST 2018
     */
    private String settle;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daybook.id
     *
     * @return the value of daybook.id
     *
     * @mbg.generated Fri Jul 27 22:56:47 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daybook.id
     *
     * @param id the value for daybook.id
     *
     * @mbg.generated Fri Jul 27 22:56:47 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daybook.money
     *
     * @return the value of daybook.money
     *
     * @mbg.generated Fri Jul 27 22:56:47 CST 2018
     */
    public BigDecimal getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daybook.money
     *
     * @param money the value for daybook.money
     *
     * @mbg.generated Fri Jul 27 22:56:47 CST 2018
     */
    public void setMoney(BigDecimal money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daybook.recorder
     *
     * @return the value of daybook.recorder
     *
     * @mbg.generated Fri Jul 27 22:56:47 CST 2018
     */
    public String getRecorder() {
        return recorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daybook.recorder
     *
     * @param recorder the value for daybook.recorder
     *
     * @mbg.generated Fri Jul 27 22:56:47 CST 2018
     */
    public void setRecorder(String recorder) {
        this.recorder = recorder == null ? null : recorder.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daybook.des
     *
     * @return the value of daybook.des
     *
     * @mbg.generated Fri Jul 27 22:56:47 CST 2018
     */
    public String getDes() {
        return des;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daybook.des
     *
     * @param des the value for daybook.des
     *
     * @mbg.generated Fri Jul 27 22:56:47 CST 2018
     */
    public void setDes(String des) {
        this.des = des == null ? null : des.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daybook.date
     *
     * @return the value of daybook.date
     *
     * @mbg.generated Fri Jul 27 22:56:47 CST 2018
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daybook.date
     *
     * @param date the value for daybook.date
     *
     * @mbg.generated Fri Jul 27 22:56:47 CST 2018
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daybook.family
     *
     * @return the value of daybook.family
     *
     * @mbg.generated Fri Jul 27 22:56:47 CST 2018
     */
    public String getFamily() {
        return family;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daybook.family
     *
     * @param family the value for daybook.family
     *
     * @mbg.generated Fri Jul 27 22:56:47 CST 2018
     */
    public void setFamily(String family) {
        this.family = family == null ? null : family.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daybook.payer
     *
     * @return the value of daybook.payer
     *
     * @mbg.generated Fri Jul 27 22:56:47 CST 2018
     */
    public String getPayer() {
        return payer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daybook.payer
     *
     * @param payer the value for daybook.payer
     *
     * @mbg.generated Fri Jul 27 22:56:47 CST 2018
     */
    public void setPayer(String payer) {
        this.payer = payer == null ? null : payer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daybook.category
     *
     * @return the value of daybook.category
     *
     * @mbg.generated Fri Jul 27 22:56:47 CST 2018
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daybook.category
     *
     * @param category the value for daybook.category
     *
     * @mbg.generated Fri Jul 27 22:56:47 CST 2018
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daybook.settle
     *
     * @return the value of daybook.settle
     *
     * @mbg.generated Fri Jul 27 22:56:47 CST 2018
     */
    public String getSettle() {
        return settle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daybook.settle
     *
     * @param settle the value for daybook.settle
     *
     * @mbg.generated Fri Jul 27 22:56:47 CST 2018
     */
    public void setSettle(String settle) {
        this.settle = settle == null ? null : settle.trim();
    }
}