package com.dawson.aaaccount.entity;

public class DaybookConsumer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daybook_consumer.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daybook_consumer.daybook
     *
     * @mbg.generated
     */
    private String daybook;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daybook_consumer.consumer
     *
     * @mbg.generated
     */
    private String consumer;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daybook_consumer.id
     *
     * @return the value of daybook_consumer.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daybook_consumer.id
     *
     * @param id the value for daybook_consumer.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daybook_consumer.daybook
     *
     * @return the value of daybook_consumer.daybook
     *
     * @mbg.generated
     */
    public String getDaybook() {
        return daybook;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daybook_consumer.daybook
     *
     * @param daybook the value for daybook_consumer.daybook
     *
     * @mbg.generated
     */
    public void setDaybook(String daybook) {
        this.daybook = daybook == null ? null : daybook.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daybook_consumer.consumer
     *
     * @return the value of daybook_consumer.consumer
     *
     * @mbg.generated
     */
    public String getConsumer() {
        return consumer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daybook_consumer.consumer
     *
     * @param consumer the value for daybook_consumer.consumer
     *
     * @mbg.generated
     */
    public void setConsumer(String consumer) {
        this.consumer = consumer == null ? null : consumer.trim();
    }
}