package com.dawson.aaaccount.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

@Entity
@Table(name="daybook")
public class Daybook implements Serializable {
	private static final long serialVersionUID = 7419229896237854702L;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daybook.id
     *
     * @mbg.generated
     */
	@Id
	@GeneratedValue(generator = "uuid")
	@GenericGenerator(name = "uuid", strategy = "uuid2")
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daybook.money
     *
     * @mbg.generated
     */
    private BigDecimal money;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daybook.recorder
     *
     * @mbg.generated
     */ 
    @ManyToOne
    @JoinColumn(name = "recorder_id")
    private User recorder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daybook.des
     *
     * @mbg.generated
     */
    private String des;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daybook.date
     *
     * @mbg.generated
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daybook.family_id
     *
     * @mbg.generated
     */
    @ManyToOne
    @JoinColumn(name = "family_id")
    private Family family;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daybook.payer_id
     *
     * @mbg.generated
     */
    @ManyToOne
    @JoinColumn(name = "payer_id")
    private User payer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daybook.category_id
     *
     * @mbg.generated
     */
    @ManyToOne
    @JoinColumn(name = "category_id")
    private Category category;
    
    @ManyToMany
    @JoinTable(name="daybook_consumer",joinColumns=@JoinColumn(name="daybook_id"),inverseJoinColumns=@JoinColumn(name="user_id"))
    private List<User> consumer;

    public Family getFamily() {
		return family;
	}

	public void setFamily(Family family) {
		this.family = family;
	}

	public User getPayer() {
		return payer;
	}

	public void setPayer(User payer) {
		this.payer = payer;
	}

	public Category getCategory() {
		return category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	public List<User> getConsumer() {
		return consumer;
	}

	public void setConsumer(List<User> consumer) {
		this.consumer = consumer;
	}

	public Settle getSettle() {
		return settle;
	}

	public void setSettle(Settle settle) {
		this.settle = settle;
	}

	public void setRecorder(User recorder) {
		this.recorder = recorder;
	}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daybook.settle_id
     *
     * @mbg.generated
     */
    @ManyToOne
    @JoinColumn(name = "settle_id")
    private Settle settle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daybook.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daybook.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daybook.pic_1
     *
     * @mbg.generated
     */
    private String pic1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daybook.pic_2
     *
     * @mbg.generated
     */
    private String pic2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daybook.pic_3
     *
     * @mbg.generated
     */
    private String pic3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daybook.id
     *
     * @return the value of daybook.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daybook.id
     *
     * @param id the value for daybook.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daybook.money
     *
     * @return the value of daybook.money
     *
     * @mbg.generated
     */
    public BigDecimal getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daybook.money
     *
     * @param money the value for daybook.money
     *
     * @mbg.generated
     */
    public void setMoney(BigDecimal money) {
        this.money = money;
    }

    

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daybook.des
     *
     * @return the value of daybook.des
     *
     * @mbg.generated
     */
    public String getDes() {
        return des;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daybook.des
     *
     * @param des the value for daybook.des
     *
     * @mbg.generated
     */
    public void setDes(String des) {
        this.des = des == null ? null : des.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daybook.date
     *
     * @return the value of daybook.date
     *
     * @mbg.generated
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daybook.date
     *
     * @param date the value for daybook.date
     *
     * @mbg.generated
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daybook.create_time
     *
     * @return the value of daybook.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daybook.create_time
     *
     * @param createTime the value for daybook.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daybook.update_time
     *
     * @return the value of daybook.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daybook.update_time
     *
     * @param updateTime the value for daybook.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daybook.pic_1
     *
     * @return the value of daybook.pic_1
     *
     * @mbg.generated
     */
    public String getPic1() {
        return pic1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daybook.pic_1
     *
     * @param pic1 the value for daybook.pic_1
     *
     * @mbg.generated
     */
    public void setPic1(String pic1) {
        this.pic1 = pic1 == null ? null : pic1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daybook.pic_2
     *
     * @return the value of daybook.pic_2
     *
     * @mbg.generated
     */
    public String getPic2() {
        return pic2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daybook.pic_2
     *
     * @param pic2 the value for daybook.pic_2
     *
     * @mbg.generated
     */
    public void setPic2(String pic2) {
        this.pic2 = pic2 == null ? null : pic2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daybook.pic_3
     *
     * @return the value of daybook.pic_3
     *
     * @mbg.generated
     */
    public String getPic3() {
        return pic3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daybook.pic_3
     *
     * @param pic3 the value for daybook.pic_3
     *
     * @mbg.generated
     */
    public void setPic3(String pic3) {
        this.pic3 = pic3 == null ? null : pic3.trim();
    }
}