package com.dawson.aaaccount.entity;

import java.util.Date;

public class DUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column duser.id
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column duser.name
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column duser.create_time
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column duser.update_time
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column duser.head_pic
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    private String headPic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column duser.auth_data
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    private String authData;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column duser.email
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column duser.phone
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column duser.login_info
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    private String loginInfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column duser.id
     *
     * @return the value of duser.id
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column duser.id
     *
     * @param id the value for duser.id
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column duser.name
     *
     * @return the value of duser.name
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column duser.name
     *
     * @param name the value for duser.name
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column duser.create_time
     *
     * @return the value of duser.create_time
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column duser.create_time
     *
     * @param createTime the value for duser.create_time
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column duser.update_time
     *
     * @return the value of duser.update_time
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column duser.update_time
     *
     * @param updateTime the value for duser.update_time
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column duser.head_pic
     *
     * @return the value of duser.head_pic
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    public String getHeadPic() {
        return headPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column duser.head_pic
     *
     * @param headPic the value for duser.head_pic
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    public void setHeadPic(String headPic) {
        this.headPic = headPic == null ? null : headPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column duser.auth_data
     *
     * @return the value of duser.auth_data
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    public String getAuthData() {
        return authData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column duser.auth_data
     *
     * @param authData the value for duser.auth_data
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    public void setAuthData(String authData) {
        this.authData = authData == null ? null : authData.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column duser.email
     *
     * @return the value of duser.email
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column duser.email
     *
     * @param email the value for duser.email
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column duser.phone
     *
     * @return the value of duser.phone
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column duser.phone
     *
     * @param phone the value for duser.phone
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column duser.login_info
     *
     * @return the value of duser.login_info
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    public String getLoginInfo() {
        return loginInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column duser.login_info
     *
     * @param loginInfo the value for duser.login_info
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    public void setLoginInfo(String loginInfo) {
        this.loginInfo = loginInfo == null ? null : loginInfo.trim();
    }
}