package com.dawson.aaaccount.entity;

public class Family {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family.id
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family.name
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family.is_temp
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    private Byte isTemp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family.creator
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    private String creator;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column family.id
     *
     * @return the value of family.id
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column family.id
     *
     * @param id the value for family.id
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column family.name
     *
     * @return the value of family.name
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column family.name
     *
     * @param name the value for family.name
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column family.is_temp
     *
     * @return the value of family.is_temp
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    public Byte getIsTemp() {
        return isTemp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column family.is_temp
     *
     * @param isTemp the value for family.is_temp
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    public void setIsTemp(Byte isTemp) {
        this.isTemp = isTemp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column family.creator
     *
     * @return the value of family.creator
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column family.creator
     *
     * @param creator the value for family.creator
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }
}