package com.dawson.aaaccount.entity;

public class FamilyMember {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family_member.id
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family_member.family
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    private String family;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family_member.member
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    private String member;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column family_member.id
     *
     * @return the value of family_member.id
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column family_member.id
     *
     * @param id the value for family_member.id
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column family_member.family
     *
     * @return the value of family_member.family
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    public String getFamily() {
        return family;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column family_member.family
     *
     * @param family the value for family_member.family
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    public void setFamily(String family) {
        this.family = family == null ? null : family.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column family_member.member
     *
     * @return the value of family_member.member
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    public String getMember() {
        return member;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column family_member.member
     *
     * @param member the value for family_member.member
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    public void setMember(String member) {
        this.member = member == null ? null : member.trim();
    }
}