package com.dawson.aaaccount.entity;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

@Entity
@Table(name="family")
public class Family  implements Serializable {
	private static final long serialVersionUID = 7419229896231522702L;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family.id
     *
     * @mbg.generated
     */
	@Id
	@GeneratedValue(generator = "uuid")
	@GenericGenerator(name = "uuid", strategy = "uuid2")
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family.is_temp
     *
     * @mbg.generated
     */
    private boolean isTemp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family.creator_id
     *
     * @mbg.generated
     */
    @ManyToOne
    @JoinColumn(name="creator_id")
    private User creator;
    
    @ManyToMany
    @JoinTable(name="family_member",joinColumns=@JoinColumn(name="family_id"),inverseJoinColumns=@JoinColumn(name="user_id"))
    private List<User> member;

    public User getCreator() {
		return creator;
	}

	public void setCreator(User creator) {
		this.creator = creator;
	}

	public List<User> getMember() {
		return member;
	}

	public void setMember(List<User> member) {
		this.member = member;
	}

	public void setTemp(boolean isTemp) {
		this.isTemp = isTemp;
	}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column family.id
     *
     * @return the value of family.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column family.id
     *
     * @param id the value for family.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column family.name
     *
     * @return the value of family.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column family.name
     *
     * @param name the value for family.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

   

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column family.create_time
     *
     * @return the value of family.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column family.create_time
     *
     * @param createTime the value for family.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column family.update_time
     *
     * @return the value of family.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column family.update_time
     *
     * @param updateTime the value for family.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}