package com.dawson.aaaccount.entity;

public class Files {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FILES.FILE_ID
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    private Long fileId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FILES.FILE_TYPE
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    private String fileType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FILES.TABLESPACE_NAME
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    private String tablespaceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FILES.TABLE_CATALOG
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    private String tableCatalog;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FILES.LOGFILE_GROUP_NAME
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    private String logfileGroupName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FILES.LOGFILE_GROUP_NUMBER
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    private Long logfileGroupNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FILES.ENGINE
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    private String engine;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FILES.FREE_EXTENTS
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    private Long freeExtents;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FILES.TOTAL_EXTENTS
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    private Long totalExtents;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FILES.EXTENT_SIZE
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    private Long extentSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FILES.INITIAL_SIZE
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    private Long initialSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FILES.MAXIMUM_SIZE
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    private Long maximumSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FILES.AUTOEXTEND_SIZE
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    private Long autoextendSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FILES.VERSION
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    private Long version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FILES.ROW_FORMAT
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    private String rowFormat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FILES.DATA_FREE
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    private Long dataFree;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FILES.STATUS
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FILES.FILE_ID
     *
     * @return the value of FILES.FILE_ID
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    public Long getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FILES.FILE_ID
     *
     * @param fileId the value for FILES.FILE_ID
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    public void setFileId(Long fileId) {
        this.fileId = fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FILES.FILE_TYPE
     *
     * @return the value of FILES.FILE_TYPE
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    public String getFileType() {
        return fileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FILES.FILE_TYPE
     *
     * @param fileType the value for FILES.FILE_TYPE
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    public void setFileType(String fileType) {
        this.fileType = fileType == null ? null : fileType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FILES.TABLESPACE_NAME
     *
     * @return the value of FILES.TABLESPACE_NAME
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    public String getTablespaceName() {
        return tablespaceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FILES.TABLESPACE_NAME
     *
     * @param tablespaceName the value for FILES.TABLESPACE_NAME
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    public void setTablespaceName(String tablespaceName) {
        this.tablespaceName = tablespaceName == null ? null : tablespaceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FILES.TABLE_CATALOG
     *
     * @return the value of FILES.TABLE_CATALOG
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    public String getTableCatalog() {
        return tableCatalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FILES.TABLE_CATALOG
     *
     * @param tableCatalog the value for FILES.TABLE_CATALOG
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    public void setTableCatalog(String tableCatalog) {
        this.tableCatalog = tableCatalog == null ? null : tableCatalog.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FILES.LOGFILE_GROUP_NAME
     *
     * @return the value of FILES.LOGFILE_GROUP_NAME
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    public String getLogfileGroupName() {
        return logfileGroupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FILES.LOGFILE_GROUP_NAME
     *
     * @param logfileGroupName the value for FILES.LOGFILE_GROUP_NAME
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    public void setLogfileGroupName(String logfileGroupName) {
        this.logfileGroupName = logfileGroupName == null ? null : logfileGroupName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FILES.LOGFILE_GROUP_NUMBER
     *
     * @return the value of FILES.LOGFILE_GROUP_NUMBER
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    public Long getLogfileGroupNumber() {
        return logfileGroupNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FILES.LOGFILE_GROUP_NUMBER
     *
     * @param logfileGroupNumber the value for FILES.LOGFILE_GROUP_NUMBER
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    public void setLogfileGroupNumber(Long logfileGroupNumber) {
        this.logfileGroupNumber = logfileGroupNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FILES.ENGINE
     *
     * @return the value of FILES.ENGINE
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    public String getEngine() {
        return engine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FILES.ENGINE
     *
     * @param engine the value for FILES.ENGINE
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    public void setEngine(String engine) {
        this.engine = engine == null ? null : engine.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FILES.FREE_EXTENTS
     *
     * @return the value of FILES.FREE_EXTENTS
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    public Long getFreeExtents() {
        return freeExtents;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FILES.FREE_EXTENTS
     *
     * @param freeExtents the value for FILES.FREE_EXTENTS
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    public void setFreeExtents(Long freeExtents) {
        this.freeExtents = freeExtents;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FILES.TOTAL_EXTENTS
     *
     * @return the value of FILES.TOTAL_EXTENTS
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    public Long getTotalExtents() {
        return totalExtents;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FILES.TOTAL_EXTENTS
     *
     * @param totalExtents the value for FILES.TOTAL_EXTENTS
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    public void setTotalExtents(Long totalExtents) {
        this.totalExtents = totalExtents;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FILES.EXTENT_SIZE
     *
     * @return the value of FILES.EXTENT_SIZE
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    public Long getExtentSize() {
        return extentSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FILES.EXTENT_SIZE
     *
     * @param extentSize the value for FILES.EXTENT_SIZE
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    public void setExtentSize(Long extentSize) {
        this.extentSize = extentSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FILES.INITIAL_SIZE
     *
     * @return the value of FILES.INITIAL_SIZE
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    public Long getInitialSize() {
        return initialSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FILES.INITIAL_SIZE
     *
     * @param initialSize the value for FILES.INITIAL_SIZE
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    public void setInitialSize(Long initialSize) {
        this.initialSize = initialSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FILES.MAXIMUM_SIZE
     *
     * @return the value of FILES.MAXIMUM_SIZE
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    public Long getMaximumSize() {
        return maximumSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FILES.MAXIMUM_SIZE
     *
     * @param maximumSize the value for FILES.MAXIMUM_SIZE
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    public void setMaximumSize(Long maximumSize) {
        this.maximumSize = maximumSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FILES.AUTOEXTEND_SIZE
     *
     * @return the value of FILES.AUTOEXTEND_SIZE
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    public Long getAutoextendSize() {
        return autoextendSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FILES.AUTOEXTEND_SIZE
     *
     * @param autoextendSize the value for FILES.AUTOEXTEND_SIZE
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    public void setAutoextendSize(Long autoextendSize) {
        this.autoextendSize = autoextendSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FILES.VERSION
     *
     * @return the value of FILES.VERSION
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    public Long getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FILES.VERSION
     *
     * @param version the value for FILES.VERSION
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    public void setVersion(Long version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FILES.ROW_FORMAT
     *
     * @return the value of FILES.ROW_FORMAT
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    public String getRowFormat() {
        return rowFormat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FILES.ROW_FORMAT
     *
     * @param rowFormat the value for FILES.ROW_FORMAT
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    public void setRowFormat(String rowFormat) {
        this.rowFormat = rowFormat == null ? null : rowFormat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FILES.DATA_FREE
     *
     * @return the value of FILES.DATA_FREE
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    public Long getDataFree() {
        return dataFree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FILES.DATA_FREE
     *
     * @param dataFree the value for FILES.DATA_FREE
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    public void setDataFree(Long dataFree) {
        this.dataFree = dataFree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FILES.STATUS
     *
     * @return the value of FILES.STATUS
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FILES.STATUS
     *
     * @param status the value for FILES.STATUS
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}