package com.dawson.aaaccount.entity;

import java.math.BigDecimal;
import java.util.Date;

public class Settle {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settle.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settle.money
     *
     * @mbg.generated
     */
    private BigDecimal money;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settle.date
     *
     * @mbg.generated
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settle.family_id
     *
     * @mbg.generated
     */
    private String familyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settle.creator_id
     *
     * @mbg.generated
     */
    private String creatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settle.start_date
     *
     * @mbg.generated
     */
    private Date startDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settle.end_date
     *
     * @mbg.generated
     */
    private Date endDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settle.settled
     *
     * @mbg.generated
     */
    private Byte settled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settle.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settle.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settle.id
     *
     * @return the value of settle.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settle.id
     *
     * @param id the value for settle.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settle.money
     *
     * @return the value of settle.money
     *
     * @mbg.generated
     */
    public BigDecimal getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settle.money
     *
     * @param money the value for settle.money
     *
     * @mbg.generated
     */
    public void setMoney(BigDecimal money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settle.date
     *
     * @return the value of settle.date
     *
     * @mbg.generated
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settle.date
     *
     * @param date the value for settle.date
     *
     * @mbg.generated
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settle.family_id
     *
     * @return the value of settle.family_id
     *
     * @mbg.generated
     */
    public String getFamilyId() {
        return familyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settle.family_id
     *
     * @param familyId the value for settle.family_id
     *
     * @mbg.generated
     */
    public void setFamilyId(String familyId) {
        this.familyId = familyId == null ? null : familyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settle.creator_id
     *
     * @return the value of settle.creator_id
     *
     * @mbg.generated
     */
    public String getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settle.creator_id
     *
     * @param creatorId the value for settle.creator_id
     *
     * @mbg.generated
     */
    public void setCreatorId(String creatorId) {
        this.creatorId = creatorId == null ? null : creatorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settle.start_date
     *
     * @return the value of settle.start_date
     *
     * @mbg.generated
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settle.start_date
     *
     * @param startDate the value for settle.start_date
     *
     * @mbg.generated
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settle.end_date
     *
     * @return the value of settle.end_date
     *
     * @mbg.generated
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settle.end_date
     *
     * @param endDate the value for settle.end_date
     *
     * @mbg.generated
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settle.settled
     *
     * @return the value of settle.settled
     *
     * @mbg.generated
     */
    public Byte getSettled() {
        return settled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settle.settled
     *
     * @param settled the value for settle.settled
     *
     * @mbg.generated
     */
    public void setSettled(Byte settled) {
        this.settled = settled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settle.create_time
     *
     * @return the value of settle.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settle.create_time
     *
     * @param createTime the value for settle.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settle.update_time
     *
     * @return the value of settle.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settle.update_time
     *
     * @param updateTime the value for settle.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}