package com.dawson.aaaccount.entity;

import java.math.BigDecimal;
import java.util.Date;

public class SettleDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settle_detail.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settle_detail.consume
     *
     * @mbg.generated
     */
    private BigDecimal consume;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settle_detail.pay
     *
     * @mbg.generated
     */
    private BigDecimal pay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settle_detail.settle
     *
     * @mbg.generated
     */
    private BigDecimal settle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settle_detail.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settle_detail.agree
     *
     * @mbg.generated
     */
    private Byte agree;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settle_detail.settle_id
     *
     * @mbg.generated
     */
    private String settleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settle_detail.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settle_detail.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settle_detail.id
     *
     * @return the value of settle_detail.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settle_detail.id
     *
     * @param id the value for settle_detail.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settle_detail.consume
     *
     * @return the value of settle_detail.consume
     *
     * @mbg.generated
     */
    public BigDecimal getConsume() {
        return consume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settle_detail.consume
     *
     * @param consume the value for settle_detail.consume
     *
     * @mbg.generated
     */
    public void setConsume(BigDecimal consume) {
        this.consume = consume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settle_detail.pay
     *
     * @return the value of settle_detail.pay
     *
     * @mbg.generated
     */
    public BigDecimal getPay() {
        return pay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settle_detail.pay
     *
     * @param pay the value for settle_detail.pay
     *
     * @mbg.generated
     */
    public void setPay(BigDecimal pay) {
        this.pay = pay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settle_detail.settle
     *
     * @return the value of settle_detail.settle
     *
     * @mbg.generated
     */
    public BigDecimal getSettle() {
        return settle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settle_detail.settle
     *
     * @param settle the value for settle_detail.settle
     *
     * @mbg.generated
     */
    public void setSettle(BigDecimal settle) {
        this.settle = settle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settle_detail.user_id
     *
     * @return the value of settle_detail.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settle_detail.user_id
     *
     * @param userId the value for settle_detail.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settle_detail.agree
     *
     * @return the value of settle_detail.agree
     *
     * @mbg.generated
     */
    public Byte getAgree() {
        return agree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settle_detail.agree
     *
     * @param agree the value for settle_detail.agree
     *
     * @mbg.generated
     */
    public void setAgree(Byte agree) {
        this.agree = agree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settle_detail.settle_id
     *
     * @return the value of settle_detail.settle_id
     *
     * @mbg.generated
     */
    public String getSettleId() {
        return settleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settle_detail.settle_id
     *
     * @param settleId the value for settle_detail.settle_id
     *
     * @mbg.generated
     */
    public void setSettleId(String settleId) {
        this.settleId = settleId == null ? null : settleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settle_detail.create_time
     *
     * @return the value of settle_detail.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settle_detail.create_time
     *
     * @param createTime the value for settle_detail.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settle_detail.update_time
     *
     * @return the value of settle_detail.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settle_detail.update_time
     *
     * @param updateTime the value for settle_detail.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}