package com.dawson.aaaccount.entity;

import java.math.BigDecimal;

public class SettleDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settle_detail.id
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settle_detail.consume
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    private BigDecimal consume;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settle_detail.pay
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    private BigDecimal pay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settle_detail.settle
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    private BigDecimal settle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settle_detail.suser
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    private String suser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settle_detail.agree
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    private Byte agree;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settle_detail.settle_id
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    private String settleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settle_detail.id
     *
     * @return the value of settle_detail.id
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settle_detail.id
     *
     * @param id the value for settle_detail.id
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settle_detail.consume
     *
     * @return the value of settle_detail.consume
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    public BigDecimal getConsume() {
        return consume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settle_detail.consume
     *
     * @param consume the value for settle_detail.consume
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    public void setConsume(BigDecimal consume) {
        this.consume = consume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settle_detail.pay
     *
     * @return the value of settle_detail.pay
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    public BigDecimal getPay() {
        return pay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settle_detail.pay
     *
     * @param pay the value for settle_detail.pay
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    public void setPay(BigDecimal pay) {
        this.pay = pay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settle_detail.settle
     *
     * @return the value of settle_detail.settle
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    public BigDecimal getSettle() {
        return settle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settle_detail.settle
     *
     * @param settle the value for settle_detail.settle
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    public void setSettle(BigDecimal settle) {
        this.settle = settle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settle_detail.suser
     *
     * @return the value of settle_detail.suser
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    public String getSuser() {
        return suser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settle_detail.suser
     *
     * @param suser the value for settle_detail.suser
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    public void setSuser(String suser) {
        this.suser = suser == null ? null : suser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settle_detail.agree
     *
     * @return the value of settle_detail.agree
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    public Byte getAgree() {
        return agree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settle_detail.agree
     *
     * @param agree the value for settle_detail.agree
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    public void setAgree(Byte agree) {
        this.agree = agree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settle_detail.settle_id
     *
     * @return the value of settle_detail.settle_id
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    public String getSettleId() {
        return settleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settle_detail.settle_id
     *
     * @param settleId the value for settle_detail.settle_id
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    public void setSettleId(String settleId) {
        this.settleId = settleId == null ? null : settleId.trim();
    }
}