package com.dawson.aaaccount.entity;

public class SystemLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_log.id
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_log.exception
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    private String exception;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_log.log_user
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    private String logUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_log.detail
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    private String detail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_log.fix_status
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    private Byte fixStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_log.location
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    private String location;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_log.id
     *
     * @return the value of system_log.id
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_log.id
     *
     * @param id the value for system_log.id
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_log.exception
     *
     * @return the value of system_log.exception
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    public String getException() {
        return exception;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_log.exception
     *
     * @param exception the value for system_log.exception
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    public void setException(String exception) {
        this.exception = exception == null ? null : exception.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_log.log_user
     *
     * @return the value of system_log.log_user
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    public String getLogUser() {
        return logUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_log.log_user
     *
     * @param logUser the value for system_log.log_user
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    public void setLogUser(String logUser) {
        this.logUser = logUser == null ? null : logUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_log.detail
     *
     * @return the value of system_log.detail
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_log.detail
     *
     * @param detail the value for system_log.detail
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_log.fix_status
     *
     * @return the value of system_log.fix_status
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    public Byte getFixStatus() {
        return fixStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_log.fix_status
     *
     * @param fixStatus the value for system_log.fix_status
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    public void setFixStatus(Byte fixStatus) {
        this.fixStatus = fixStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_log.location
     *
     * @return the value of system_log.location
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_log.location
     *
     * @param location the value for system_log.location
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }
}