package com.dawson.aaaccount.domain;

import com.dawson.aaaccount.entity.DaybookConsumer;

public interface DaybookConsumerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daybook_consumer
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daybook_consumer
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    int insert(DaybookConsumer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daybook_consumer
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    int insertSelective(DaybookConsumer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daybook_consumer
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    DaybookConsumer selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daybook_consumer
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    int updateByPrimaryKeySelective(DaybookConsumer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daybook_consumer
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    int updateByPrimaryKey(DaybookConsumer record);
}