package com.dawson.aaaccount.domain;

import com.dawson.aaaccount.entity.DaybookPicture;

public interface DaybookPictureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daybook_picture
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daybook_picture
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    int insert(DaybookPicture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daybook_picture
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    int insertSelective(DaybookPicture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daybook_picture
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    DaybookPicture selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daybook_picture
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    int updateByPrimaryKeySelective(DaybookPicture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daybook_picture
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    int updateByPrimaryKey(DaybookPicture record);
}