package com.dawson.aaaccount.domain;

import java.util.List;

import com.dawson.aaaccount.entity.DayBook;

public interface DayBookMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daybook
     *
     * @mbg.generated Fri Jul 27 22:56:47 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daybook
     *
     * @mbg.generated Fri Jul 27 22:56:47 CST 2018
     */
    int insert(DayBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daybook
     *
     * @mbg.generated Fri Jul 27 22:56:47 CST 2018
     */
    int insertSelective(DayBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daybook
     *
     * @mbg.generated Fri Jul 27 22:56:47 CST 2018
     */
    DayBook selectByPrimaryKey(String id);
    
    List<DayBook> getAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daybook
     *
     * @mbg.generated Fri Jul 27 22:56:47 CST 2018
     */
    int updateByPrimaryKeySelective(DayBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daybook
     *
     * @mbg.generated Fri Jul 27 22:56:47 CST 2018
     */
    int updateByPrimaryKey(DayBook record);
}