package com.dawson.aaaccount.domain;

import java.util.List;

import com.dawson.aaaccount.entity.Daybook;

public interface DaybookMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daybook
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daybook
     *
     * @mbg.generated
     */
    int insert(Daybook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daybook
     *
     * @mbg.generated
     */
    int insertSelective(Daybook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daybook
     *
     * @mbg.generated
     */
    Daybook selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daybook
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Daybook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daybook
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Daybook record);
    
    List<Daybook> selectByHost(String fid,String uid,int offset,int rows);
}