package com.dawson.aaaccount.domain;

import com.dawson.aaaccount.entity.DUser;

public interface DUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table duser
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table duser
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    int insert(DUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table duser
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    int insertSelective(DUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table duser
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    DUser selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table duser
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    int updateByPrimaryKeySelective(DUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table duser
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    int updateByPrimaryKey(DUser record);
}