package com.dawson.aaaccount.domain;

import com.dawson.aaaccount.entity.FamilyMember;

public interface FamilyMemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family_member
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family_member
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    int insert(FamilyMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family_member
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    int insertSelective(FamilyMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family_member
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    FamilyMember selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family_member
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    int updateByPrimaryKeySelective(FamilyMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family_member
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    int updateByPrimaryKey(FamilyMember record);
}