package com.dawson.aaaccount.domain;

import com.dawson.aaaccount.entity.Family;

public interface FamilyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    int insert(Family record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    int insertSelective(Family record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    Family selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    int updateByPrimaryKeySelective(Family record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    int updateByPrimaryKey(Family record);
}