package com.dawson.aaaccount.domain;

import java.util.List;

import com.dawson.aaaccount.entity.Family;

public interface FamilyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family
     *
     * @mbg.generated
     */
    int insert(Family record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family
     *
     * @mbg.generated
     */
    int insertSelective(Family record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family
     *
     * @mbg.generated
     */
    Family selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Family record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Family record);
    
    List<Family> selectByUserId(String userid);
}