package com.dawson.aaaccount.domain;

import com.dawson.aaaccount.entity.Files;

public interface FilesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table files
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table files
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    int insert(Files record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table files
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    int insertSelective(Files record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table files
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    Files selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table files
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    int updateByPrimaryKeySelective(Files record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table files
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    int updateByPrimaryKey(Files record);
}