package com.dawson.aaaccount.domain;

import com.dawson.aaaccount.entity.SettleDetail;

public interface SettleDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settle_detail
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settle_detail
     *
     * @mbg.generated
     */
    int insert(SettleDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settle_detail
     *
     * @mbg.generated
     */
    int insertSelective(SettleDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settle_detail
     *
     * @mbg.generated
     */
    SettleDetail selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settle_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SettleDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settle_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SettleDetail record);
}