package com.dawson.aaaccount.domain;

import com.dawson.aaaccount.entity.Settle;

public interface SettleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settle
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settle
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    int insert(Settle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settle
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    int insertSelective(Settle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settle
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    Settle selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settle
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    int updateByPrimaryKeySelective(Settle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settle
     *
     * @mbg.generated Sun Jul 29 17:49:52 CST 2018
     */
    int updateByPrimaryKey(Settle record);
}